name: sc

services:
  sc-product-db:
    extends:
      file: ./server/product-service/assets/docker-compose.product.yml
      service: postgres-product

  sc-user-db:
    extends:
      file: ./server/user-service/assets/docker-compose.user.yml
      service: postgres-user

  sc-auth-db:
    extends:
      file: ./server/auth-service/assets/docker-compose.auth.yml
      service: postgres-auth

  minio:
    extends:
      file: ./shared/assets/docker-compose.storage.yml
      service: minio

  minio-init:
    extends:
      file: ./shared/assets/docker-compose.storage.yml
      service: minio-init

  sc-product-service:
    extends:
      file: ./server/product-service/assets/docker-compose.product.yml
      service: product-service

  sc-auth-service:
    extends:
      file: ./server/auth-service/assets/docker-compose.auth.yml
      service: auth-service

  sc-user-service:
    extends:
      file: ./server/user-service/assets/docker-compose.user.yml
      service: user-service

#  mvp in process...
#  sc-client:
#    extends:
#      file: ./client/sc-client/assets/docker-compose.client.yml
#      service: sc-client

  nginx:
    extends:
      file: ./nginx/assets/docker-compose.nginx.yml
      service: nginx

  sc-client-admin:
    extends:
      file: ./client/sc-admin/assets/docker-compose.admin.yml
      service: sc-admin

volumes:
  postgres-product-data:
  postgres-user-data:
  postgres-auth-data:
  minio-data:
